import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';

const LanguageContext = createContext(null);

const _rawApi = import.meta.env.VITE_API_URL || '/api/';
const API_URL = _rawApi.endsWith('/') ? _rawApi : _rawApi + '/';

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign out',
    'nav.admin': 'Admin Panel',
    'hero.tagline': '100% Organic · Farm to Table · Hyderabad',
    'hero.viewAll': 'View All Products',
    'hero.cta': 'Shop Now',
    'hero.title': 'Pure from Nature,\nCrafted for You',
    'hero.subtitle': 'Discover the finest organic spices, teas, ghee & oils sourced directly from certified Indian farms — unprocessed, uncompromised.',
    'categories.kicker': 'What We Offer',
    'categories.title': 'Our Collections',
    'categories.subtitle': 'Every category, curated for purity and flavour from farms we personally trust.',
    'categories.shop': 'Shop {cat} →',
    'featured.kicker': 'Bestsellers',
    'featured.title': 'Featured Products',
    'featured.viewAll': 'View All',
    'featured.add': 'Add',
    'why.kicker': 'Why BR Fresh?',
    'why.title': 'Our Promise to You',
    'testimonials.kicker': 'Customer Love',
    'testimonials.title': 'What Our Customers Say',
    'newsletter.title': 'Stay in the Loop',
    'newsletter.subtitle': 'Join our community for seasonal recipes, farm stories, exclusive offers and new product launches.',
    'newsletter.thanks': "🌿 Thank you! You're on the list.",
    'newsletter.subscribe': 'Subscribe',
    'newsletter.placeholder': 'your@email.com',
    'newsletter.note': 'No spam, ever. Unsubscribe anytime.',
    'footer.explore': 'Explore',
    'footer.contact': 'Contact',
    'footer.tagline': 'Pure, certified organic products sourced directly from Indian farms. No compromise on quality, no compromise on nature.',
    'footer.rights': 'All rights reserved.',
    'footer.made': 'Made with 🌿 in India',
    'checkout.emptyTitle': 'Your cart is empty',
    'checkout.emptyCta': 'Browse Products',
    'checkout.title': 'Checkout',
    'checkout.contact': 'Contact Details',
    'checkout.fullName': 'Full Name *',
    'checkout.phone': 'Phone Number *',
    'checkout.email': 'Email (optional)',
    'checkout.delivery': 'Delivery Address',
    'checkout.useLocation': 'Use My Location',
    'checkout.detecting': 'Detecting...',
    'checkout.locationPinned': 'Location pinned',
    'checkout.viewMaps': 'View on Google Maps',
    'checkout.addressLine': 'Address Line *',
    'checkout.city': 'City *',
    'checkout.state': 'State *',
    'checkout.pincode': 'Pincode *',
    'checkout.payment': 'Payment Method',
    'checkout.upi': 'UPI Payment',
    'checkout.upiDesc': 'Pay now via UPI & upload screenshot',
    'checkout.cod': 'Cash on Delivery',
    'checkout.codDesc': 'Pay cash when order arrives',
    'checkout.payTo': 'Pay to our UPI ID',
    'checkout.amount': 'Amount',
    'checkout.uploadHint': 'Then upload the payment screenshot below for confirmation.',
    'checkout.uploadRequired': 'Please upload your UPI payment screenshot to continue.',
    'checkout.uploadBtn': 'Upload Payment Screenshot',
    'checkout.uploadSub': 'JPG, PNG accepted',
    'checkout.agentTitle': 'Our agent will call you to confirm',
    'checkout.agentDesc': 'After placing the order, our team will call you on {phone} to confirm the order before dispatch. Please keep your phone reachable.',
    'checkout.geoUnsupported': 'Geolocation not supported by your browser.',
    'checkout.geoError': 'Could not get location. Please allow location access and try again.',
    'checkout.summary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.shippingDiscuss': 'To be discussed',
    'checkout.shippingFree': 'Free',
    'checkout.total': 'Total',
    'checkout.placeCod': 'Place COD Order',
    'checkout.confirmUpi': 'Confirm UPI Order on WhatsApp',
    'checkout.placing': 'Placing Order…',
    'checkout.backToCart': '← Back to Cart',
    'checkout.noteCod': 'Our agent will call you to confirm before dispatch.',
    'checkout.noteUpi': 'Your order + payment screenshot will be sent via WhatsApp.',
    'checkout.loginRequiredTitle': 'Sign in required',
    'checkout.loginRequiredBody': 'Booking requires phone confirmation. Please sign in with your phone number to place this order.',
    'checkout.loginCta': 'Sign in',
    'checkout.phoneMismatch': 'Please use your signed-in phone number to place the order.',
    'checkout.phoneLocked': 'Phone number verified. To change it, sign out and sign in again.',
    'checkout.registeredNumber': 'your registered number',
    'checkout.namePlaceholder': 'Rahul Verma',
    'checkout.phonePlaceholder': '9876543210',
    'checkout.emailPlaceholder': 'rahul@email.com',
    'checkout.addressPlaceholder': 'House no, Street, Area',
    'checkout.cityPlaceholder': 'Bangalore',
    'checkout.statePlaceholder': 'Karnataka',
    'checkout.pincodePlaceholder': '560001',
    'whatsapp.newCod': '🛒 *New COD Order — BR Fresh Extracts*',
    'whatsapp.newUpi': '🛒 *New UPI Order — BR Fresh Extracts*',
    'whatsapp.orderId': '*Order ID:* {id}',
    'whatsapp.name': '*Name:* {name}',
    'whatsapp.phone': '*Phone:* {phone}',
    'whatsapp.email': '*Email:* {email}',
    'whatsapp.addressTitle': '*Delivery Address:*',
    'whatsapp.location': '📍 Location: {link}',
    'whatsapp.detailsTitle': '*Order Details:*',
    'whatsapp.subtotal': '*Subtotal:* ₹{amount}',
    'whatsapp.shipping': '*Shipping:* {amount}',
    'whatsapp.shippingDiscuss': '📦 Shipping charges will be confirmed before dispatch.',
    'whatsapp.total': '*Grand Total:* ₹{amount}',
    'whatsapp.codNote': '🚚 *Payment: Cash on Delivery* — Please call customer to confirm order.',
    'whatsapp.upiNote': '💳 *Payment: UPI* — Payment screenshot attached. Please verify and approve.',
    'shop.kicker': 'All Products',
    'shop.title': 'Our Store',
    'shop.subtitle': 'Pure, organic goodness — straight from nature to your doorstep.',
    'shop.searchPlaceholder': 'Search products...',
    'shop.filters': 'Filters',
    'shop.all': 'All',
    'shop.bestseller': 'Bestseller',
    'shop.addToCart': 'Add to Cart',
    'shop.productsFound': '{count} product{plural} found',
    'shop.noProducts': 'No products found',
    'shop.tryDifferent': 'Try a different search or category.',
    'shop.sortDefault': 'Sort: Default',
    'shop.sortPriceLow': 'Price: Low to High',
    'shop.sortPriceHigh': 'Price: High to Low',
    'shop.sortName': 'Name: A–Z',
    'shop.sortNew': 'Newest First',
    'shop.soldOut': 'Sold Out',
    'cart.emptyTitle': 'Your cart is empty',
    'cart.emptySubtitle': 'Add some organic goodness to get started.',
    'cart.emptyCta': 'Browse Products',
    'cart.title': 'Your Cart',
    'cart.itemsLabel': '({count} item{plural})',
    'cart.clearConfirm': 'Clear your cart?',
    'cart.clearButton': 'Clear cart',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.free': 'Free',
    'cart.freePrompt': 'Add ₹{amount} more for free shipping!',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continue': 'Continue Shopping',
    'login.panelSubtitle': 'Pure from Nature, Crafted for You — join our community of conscious living.',
    'login.panelBullet1': 'Access exclusive member offers',
    'login.panelBullet2': 'Track your orders',
    'login.panelBullet3': 'Get seasonal recipes & tips',
    'login.welcome': 'Welcome back',
    'login.create': 'Create an account',
    'login.signInSub': 'Sign in to your account',
    'login.signUpSub': 'Join the BR Fresh Extracts community',
    'login.customerTab': 'Customer OTP',
    'login.adminTab': 'Admin Login',
    'login.adminTitle': 'Admin Sign In',
    'login.adminSub': 'Access the admin dashboard',
    'login.fullName': 'Full Name',
    'login.phone': 'Phone Number',
    'login.phoneOrEmail': 'Phone (customers) / Email (admin)',
    'login.phonePlaceholder': '10-digit phone number',
    'login.emailOptional': 'Email (optional)',
    'login.adminEmail': 'Admin Email',
    'login.adminPassword': 'Admin Password',
    'login.namePlaceholder': 'Your name',
    'login.emailPlaceholder': 'you@example.com',
    'login.otpPlaceholder': '123456',
    'login.adminEmailPlaceholder': 'admin@example.com',
    'login.passwordPlaceholder': '••••••••',
    'login.password': 'Password',
    'login.sendOtp': 'Send OTP',
    'login.verifyOtp': 'Verify OTP',
    'login.otpLabel': 'OTP Code',
    'login.resendOtp': 'Resend OTP',
    'login.changePhone': '← Change number',
    'login.otpSentTo': 'OTP sent to',
    'login.otpHint': 'Enter the 6-digit code sent to your phone',
    'login.firebaseMissing': 'Please add Firebase keys first, then try again.',
    'login.adminSignIn': 'Sign In as Admin',
    'login.signIn': 'Sign In',
    'login.createAccount': 'Create Account',
    'login.noAccount': "Don't have an account? ",
    'login.haveAccount': 'Already have an account? ',
    'login.signUpLink': 'Sign up',
    'login.signInLink': 'Sign in',
  },
  hi: {
    'shop.kicker': 'सभी उत्पाद',
    'shop.title': 'हमारी दुकान',
    'shop.subtitle': 'शुद्ध ऑर्गेनिक अच्छाई — प्रकृति से सीधे आपके दरवाजे तक।',
    'shop.searchPlaceholder': 'उत्पाद खोजें...',
    'shop.filters': 'फ़िल्टर',
    'shop.all': 'सभी',
    'shop.bestseller': 'बेस्टसेलर',
    'shop.addToCart': 'कार्ट में जोड़ें',
    'shop.productsFound': '{count} उत्पाद मिले',
    'shop.noProducts': 'कोई उत्पाद नहीं मिला',
    'shop.tryDifferent': 'अलग खोज या श्रेणी आज़माएं।',
    'shop.sortDefault': 'क्रम: डिफ़ॉल्ट',
    'shop.sortPriceLow': 'कीमत: कम से ज़्यादा',
    'shop.sortPriceHigh': 'कीमत: ज़्यादा से कम',
    'shop.sortName': 'नाम: A–Z',
    'shop.sortNew': 'नवीनतम पहले',
    'shop.soldOut': 'स्टॉक खत्म',
    'cart.emptyTitle': 'आपकी कार्ट खाली है',
    'cart.emptySubtitle': 'शुरुआत के लिए कुछ ऑर्गेनिक अच्छाई जोड़ें।',
    'cart.emptyCta': 'उत्पाद देखें',
    'cart.title': 'आपकी कार्ट',
    'cart.itemsLabel': '({count} आइटम)',
    'cart.clearConfirm': 'कार्ट साफ करें?',
    'cart.clearButton': 'कार्ट साफ करें',
    'cart.summary': 'ऑर्डर सारांश',
    'cart.subtotal': 'उप-योग',
    'cart.shipping': 'शिपिंग',
    'cart.free': 'मुफ़्त',
    'cart.freePrompt': 'मुफ़्त शिपिंग के लिए ₹{amount} और जोड़ें!',
    'cart.total': 'कुल',
    'cart.checkout': 'चेकआउट करें',
    'cart.continue': 'खरीदारी जारी रखें',
    'login.panelSubtitle': 'प्रकृति की शुद्धता — सचेत जीवन के लिए हमारे समुदाय से जुड़ें।',
    'login.panelBullet1': 'विशेष सदस्य ऑफ़र पाएं',
    'login.panelBullet2': 'अपने ऑर्डर ट्रैक करें',
    'login.panelBullet3': 'सीजनल रेसिपी और टिप्स पाएं',
    'login.welcome': 'वापस स्वागत है',
    'login.create': 'खाता बनाएं',
    'login.signInSub': 'अपने खाते में साइन इन करें',
    'login.signUpSub': 'BR Fresh Extracts समुदाय से जुड़ें',
    'login.phoneOrEmail': 'फोन (ग्राहक) / ईमेल (एडमिन)',
    'login.password': 'पासवर्ड',
    'login.signIn': 'साइन इन करें',
    'login.createAccount': 'खाता बनाएं',
    'nav.home': 'होम',
    'nav.shop': 'दुकान',
    'nav.signIn': 'साइन इन',
    'nav.signOut': 'साइन आउट',
    'nav.admin': 'एडमिन पैनल',
    'hero.tagline': '100% ऑर्गेनिक · फार्म से आपकी टेबल तक · नई दिल्ली',
    'hero.viewAll': 'सभी उत्पाद देखें',
    'hero.cta': 'अभी खरीदें',
    'hero.title': 'प्रकृति की शुद्धता,\nआपके लिए तैयार',
    'hero.subtitle': 'प्रमाणित भारतीय फार्म से सीधे चुने गए ऑर्गेनिक मसाले, चाय, घी और तेल — शुद्ध और असली।',
    'categories.kicker': 'हम क्या पेश करते हैं',
    'categories.title': 'हमारे कलेक्शन',
    'categories.subtitle': 'हर श्रेणी शुद्धता और स्वाद के लिए विशेष रूप से चुनी गई।',
    'categories.shop': '{cat} खरीदें →',
    'featured.kicker': 'बेस्टसेलर',
    'featured.title': 'चुनिंदा उत्पाद',
    'featured.viewAll': 'सभी देखें',
    'featured.add': 'जोड़ें',
    'why.kicker': 'BR Fresh क्यों?',
    'why.title': 'आपसे हमारा वादा',
    'testimonials.kicker': 'ग्राहकों का प्यार',
    'testimonials.title': 'हमारे ग्राहक क्या कहते हैं',
    'newsletter.title': 'जुड़े रहें',
    'newsletter.subtitle': 'सीजनल रेसिपी, फार्म कहानियां और नए प्रोडक्ट्स की जानकारी पाएं।',
    'newsletter.thanks': '🌿 धन्यवाद! आप सूची में हैं।',
    'newsletter.subscribe': 'सब्सक्राइब',
    'newsletter.placeholder': 'आपका@ईमेल.कॉम',
    'newsletter.note': 'कोई स्पैम नहीं। कभी भी अनसब्सक्राइब करें।',
    'footer.explore': 'खोजें',
    'footer.contact': 'संपर्क',
    'footer.tagline': 'शुद्ध, प्रमाणित ऑर्गेनिक उत्पाद सीधे भारतीय फार्म से।',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.made': 'भारत में 🌿 के साथ बनाया गया',
    'checkout.emptyTitle': 'आपकी कार्ट खाली है',
    'checkout.emptyCta': 'उत्पाद देखें',
    'checkout.title': 'चेकआउट',
    'checkout.contact': 'संपर्क विवरण',
    'checkout.fullName': 'पूरा नाम *',
    'checkout.phone': 'फोन नंबर *',
    'checkout.email': 'ईमेल (वैकल्पिक)',
    'checkout.delivery': 'डिलीवरी पता',
    'checkout.useLocation': 'मेरी लोकेशन उपयोग करें',
    'checkout.detecting': 'लोकेशन ढूंढी जा रही है...',
    'checkout.locationPinned': 'लोकेशन सेव हो गई',
    'checkout.viewMaps': 'गूगल मैप्स पर देखें',
    'checkout.addressLine': 'पता *',
    'checkout.city': 'शहर *',
    'checkout.state': 'राज्य *',
    'checkout.pincode': 'पिनकोड *',
    'checkout.payment': 'भुगतान तरीका',
    'checkout.upi': 'UPI भुगतान',
    'checkout.upiDesc': 'UPI से भुगतान करें और स्क्रीनशॉट अपलोड करें',
    'checkout.cod': 'कैश ऑन डिलीवरी',
    'checkout.codDesc': 'डिलीवरी पर नकद भुगतान',
    'checkout.payTo': 'UPI ID पर भुगतान करें',
    'checkout.amount': 'राशि',
    'checkout.uploadHint': 'फिर भुगतान का स्क्रीनशॉट अपलोड करें।',
    'checkout.uploadRequired': 'कृपया UPI भुगतान का स्क्रीनशॉट अपलोड करें।',
    'checkout.uploadBtn': 'भुगतान स्क्रीनशॉट अपलोड करें',
    'checkout.uploadSub': 'JPG, PNG स्वीकार्य',
    'checkout.agentTitle': 'हमारा एजेंट पुष्टि के लिए कॉल करेगा',
    'checkout.agentDesc': 'ऑर्डर के बाद हमारी टीम {phone} पर कॉल करेगी। कृपया फोन उपलब्ध रखें।',
    'checkout.geoUnsupported': 'आपके ब्राउज़र में लोकेशन सपोर्ट नहीं है।',
    'checkout.geoError': 'लोकेशन नहीं मिल पाई। कृपया अनुमति दें और फिर कोशिश करें।',
    'checkout.summary': 'ऑर्डर सारांश',
    'checkout.subtotal': 'उप-योग',
    'checkout.shipping': 'शिपिंग',
    'checkout.shippingDiscuss': 'बात करके तय होगा',
    'checkout.shippingFree': 'मुफ़्त',
    'checkout.total': 'कुल',
    'checkout.placeCod': 'COD ऑर्डर करें',
    'checkout.confirmUpi': 'WhatsApp पर UPI ऑर्डर पुष्टि करें',
    'checkout.placing': 'ऑर्डर हो रहा है…',
    'checkout.backToCart': '← कार्ट पर वापस जाएँ',
    'checkout.noteCod': 'डिस्पैच से पहले पुष्टि के लिए कॉल आएगा।',
    'checkout.noteUpi': 'ऑर्डर और भुगतान स्क्रीनशॉट WhatsApp पर भेजे जाएंगे।',
    'checkout.loginRequiredTitle': 'साइन इन ज़रूरी है',
    'checkout.loginRequiredBody': 'बुकिंग के लिए फोन पुष्टि अनिवार्य है। कृपया अपने फोन नंबर से साइन इन करें।',
    'checkout.loginCta': 'साइन इन करें',
    'checkout.phoneMismatch': 'कृपया ऑर्डर के लिए वही फोन नंबर उपयोग करें जिससे आपने साइन इन किया है।',
    'checkout.phoneLocked': 'फोन नंबर सत्यापित है। बदलने के लिए साइन आउट करके फिर साइन इन करें।',
    'checkout.registeredNumber': 'आपका पंजीकृत नंबर',
    'checkout.namePlaceholder': 'उदा. राहुल वर्मा',
    'checkout.phonePlaceholder': '9876543210',
    'checkout.emailPlaceholder': 'rahul@email.com',
    'checkout.addressPlaceholder': 'घर नं., गली, क्षेत्र',
    'checkout.cityPlaceholder': 'बेंगलुरु',
    'checkout.statePlaceholder': 'कर्नाटक',
    'checkout.pincodePlaceholder': '560001',
    'whatsapp.newCod': '🛒 *नई COD ऑर्डर — BR Fresh Extracts*',
    'whatsapp.newUpi': '🛒 *नई UPI ऑर्डर — BR Fresh Extracts*',
    'whatsapp.orderId': '*ऑर्डर ID:* {id}',
    'whatsapp.name': '*नाम:* {name}',
    'whatsapp.phone': '*फोन:* {phone}',
    'whatsapp.email': '*ईमेल:* {email}',
    'whatsapp.addressTitle': '*डिलीवरी पता:*',
    'whatsapp.location': '📍 लोकेशन: {link}',
    'whatsapp.detailsTitle': '*ऑर्डर विवरण:*',
    'whatsapp.subtotal': '*उप-योग:* ₹{amount}',
    'whatsapp.shipping': '*शिपिंग:* {amount}',
    'whatsapp.shippingDiscuss': '📦 शिपिंग चार्ज डिस्पैच से पहले बताया जाएगा।',
    'whatsapp.total': '*कुल:* ₹{amount}',
    'whatsapp.codNote': '🚚 *भुगतान: COD* — कृपया ग्राहक को कॉल करके पुष्टि करें।',
    'whatsapp.upiNote': '💳 *भुगतान: UPI* — कृपया स्क्रीनशॉट जाँचकर पुष्टि करें।',
    'login.customerTab': 'कस्टमर OTP',
    'login.adminTab': 'एडमिन लॉगिन',
    'login.adminTitle': 'एडमिन साइन इन',
    'login.adminSub': 'एडमिन डैशबोर्ड एक्सेस करें',
    'login.fullName': 'पूरा नाम',
    'login.phone': 'फोन नंबर',
    'login.phonePlaceholder': '10 अंकों का फोन नंबर',
    'login.emailOptional': 'ईमेल (वैकल्पिक)',
    'login.adminEmail': 'एडमिन ईमेल',
    'login.adminPassword': 'एडमिन पासवर्ड',
    'login.namePlaceholder': 'उदा. राहुल वर्मा',
    'login.emailPlaceholder': 'you@example.com',
    'login.otpPlaceholder': '123456',
    'login.adminEmailPlaceholder': 'admin@example.com',
    'login.passwordPlaceholder': '••••••••',
    'login.sendOtp': 'OTP भेजें',
    'login.verifyOtp': 'OTP सत्यापित करें',
    'login.otpLabel': 'OTP कोड',
    'login.resendOtp': 'OTP फिर से भेजें',
    'login.changePhone': '← नंबर बदलें',
    'login.otpSentTo': 'OTP भेजा गया',
    'login.otpHint': 'आपके फ़ोन पर भेजा गया 6-अंकीय कोड दर्ज करें',
    'login.firebaseMissing': 'Firebase keys जोड़ें और फिर कोशिश करें।',
    'login.adminSignIn': 'एडमिन के रूप में साइन इन करें',
    'login.noAccount': "खाता नहीं है? ",
    'login.haveAccount': 'पहले से खाता है? ',
    'login.signUpLink': 'साइन अप करें',
    'login.signInLink': 'साइन इन करें',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.shop': 'షాప్',
    'nav.signIn': 'సైన్ ఇన్',
    'nav.signOut': 'సైన్ అవుట్',
    'nav.admin': 'అడ్మిన్ ప్యానెల్',
    'hero.tagline': '100% ఆర్గానిక్ · ఫారం నుంచి మీ టేబుల్‌కి · న్యూఢిల్లీ',
    'hero.viewAll': 'అన్ని ఉత్పత్తులు చూడండి',
    'hero.cta': 'ఇప్పుడే కొనండి',
    'hero.title': 'ప్రకృతి నుండి స్వచ్ఛత,\nమీ కోసం సిద్ధం',
    'hero.subtitle': 'సర్టిఫైడ్ భారతీయ రైతుల నుండి ఆర్గానిక్ మసాలాలు, టీలు, నెయ్యి & నూనెలు — స్వచ్ఛంగా.',
    'categories.kicker': 'మేము అందించేది',
    'categories.title': 'మా కలెక్షన్స్',
    'categories.subtitle': 'ప్రతి కేటగిరీని స్వచ్ఛత మరియు రుచికి ఎంపిక చేశాం.',
    'categories.shop': '{cat} కొనండి →',
    'featured.kicker': 'బెస్ట్‌సెల్లర్స్',
    'featured.title': 'ఫీచర్డ్ ప్రొడక్ట్స్',
    'featured.viewAll': 'అన్నీ చూడండి',
    'featured.add': 'జోడించండి',
    'why.kicker': 'BR Fresh ఎందుకు?',
    'why.title': 'మీకు మా హామీ',
    'testimonials.kicker': 'కస్టమర్ ప్రేమ',
    'testimonials.title': 'మా కస్టమర్లు ఏమంటున్నారు',
    'newsletter.title': 'అప్‌డేట్స్ పొందండి',
    'newsletter.subtitle': 'సీజనల్ రెసిపీలు, ఫారం కథలు, ఆఫర్లు మరియు కొత్త ఉత్పత్తుల సమాచారం.',
    'newsletter.thanks': '🌿 ధన్యవాదాలు! మీరు లిస్ట్‌లో ఉన్నారు.',
    'newsletter.subscribe': 'సబ్‌స్క్రైబ్',
    'newsletter.placeholder': 'మీ@email.com',
    'newsletter.note': 'స్పామ్ లేదు. ఎప్పుడైనా అన్సబ్‌స్క్రైబ్ చేయండి.',
    'footer.explore': 'అన్వేషించండి',
    'footer.contact': 'సంప్రదించండి',
    'footer.tagline': 'శుద్ధమైన సర్టిఫైడ్ ఆర్గానిక్ ఉత్పత్తులు భారతీయ ఫార్మ్‌ల నుండి.',
    'footer.rights': 'అన్ని హక్కులు పరిరక్షించబడ్డాయి.',
    'footer.made': 'భారతదేశంలో 🌿తో తయారు',
    'shop.kicker': 'అన్ని ఉత్పత్తులు',
    'shop.title': 'మా స్టోర్',
    'shop.subtitle': 'స్వచ్ఛమైన ఆర్గానిక్ మేలిమి — ప్రకృతి నుండి మీ ముంగిటికి.',
    'shop.searchPlaceholder': 'ఉత్పత్తి వెతకండి...',
    'shop.filters': 'ఫిల్టర్లు',
    'shop.all': 'అన్నీ',
    'shop.bestseller': 'బెస్ట్‌సెల్లర్',
    'shop.addToCart': 'కార్ట్‌కు జోడించండి',
    'shop.productsFound': '{count} ఉత్పత్తులు దొరికాయి',
    'shop.noProducts': 'ఉత్పత్తులు కనుగొనబడలేదు',
    'shop.tryDifferent': 'వేరే శోధన లేదా వర్గాన్ని ప్రయత్నించండి.',
    'shop.sortDefault': 'క్రమం: డిఫాల్ట్',
    'shop.sortPriceLow': 'ధర: తక్కువ నుండి ఎక్కువ',
    'shop.sortPriceHigh': 'ధర: ఎక్కువ నుండి తక్కువ',
    'shop.sortName': 'పేరు: A–Z',
    'shop.sortNew': 'కొత్తవి ముందు',
    'shop.soldOut': 'స్టాక్ లేదు',
    'cart.emptyTitle': 'మీ కార్ట్ ఖాళీగా ఉంది',
    'cart.emptySubtitle': 'ప్రారంభించడానికి కొన్ని ఆర్గానిక్ మేలిమిని జోడించండి.',
    'cart.emptyCta': 'ఉత్పత్తులు చూడండి',
    'cart.title': 'మీ కార్ట్',
    'cart.itemsLabel': '({count} ఐటమ్‌లు)',
    'cart.clearConfirm': 'కార్ట్ క్లియర్ చేయాలా?',
    'cart.clearButton': 'కార్ట్ క్లియర్ చేయండి',
    'cart.summary': 'ఆర్డర్ సారాంశం',
    'cart.subtotal': 'సబ్‌టోటల్',
    'cart.shipping': 'షిప్పింగ్',
    'cart.free': 'ఉచితం',
    'cart.freePrompt': 'ఉచిత షిప్పింగ్ కోసం ₹{amount} మరింత జోడించండి!',
    'cart.total': 'మొత్తం',
    'cart.checkout': 'చెక్‌అవుట్',
    'cart.continue': 'షాపింగ్ కొనసాగించండి',
    'login.panelSubtitle': 'ప్రకృతి స్వచ్ఛత — సచేతన జీవనానికి మా సమాజంలో చేరండి.',
    'login.panelBullet1': 'ప్రత్యేక సభ్య ఆఫర్లు పొందండి',
    'login.panelBullet2': 'మీ ఆర్డర్లు ట్రాక్ చేయండి',
    'login.panelBullet3': 'సీజనల్ రెసిపీలు & చిట్కాలు పొందండి',
    'login.welcome': 'తిరిగి స్వాగతం',
    'login.create': 'ఖాతా తెరవండి',
    'login.signInSub': 'మీ ఖాతాలోకి సైన్ ఇన్ చేయండి',
    'login.signUpSub': 'BR Fresh Extracts సమాజంలో చేరండి',
    'login.phoneOrEmail': 'ఫోన్ (కస్టమర్) / ఈమెయిల్ (అడ్మిన్)',
    'login.password': 'పాస్‌వర్డ్',
    'login.signIn': 'సైన్ ఇన్',
    'login.createAccount': 'ఖాతా తెరవండి',
    'checkout.emptyTitle': 'మీ కార్ట్ ఖాళీగా ఉంది',
    'checkout.emptyCta': 'ఉత్పత్తులు చూడండి',
    'checkout.title': 'చెక్‌అవుట్',
    'checkout.contact': 'సంప్రదింపు వివరాలు',
    'checkout.fullName': 'పూర్తి పేరు *',
    'checkout.phone': 'ఫోన్ నంబర్ *',
    'checkout.email': 'ఈమెయిల్ (ఐచ్ఛికం)',
    'checkout.delivery': 'డెలివరీ చిరునామా',
    'checkout.useLocation': 'నా లొకేషన్ ఉపయోగించండి',
    'checkout.detecting': 'లొకేషన్ గుర్తిస్తోంది...',
    'checkout.locationPinned': 'లొకేషన్ సేవ్ అయ్యింది',
    'checkout.viewMaps': 'Google Maps లో చూడండి',
    'checkout.addressLine': 'చిరునామా *',
    'checkout.city': 'నగరం *',
    'checkout.state': 'రాష్ట్రం *',
    'checkout.pincode': 'పిన్‌కోడ్ *',
    'checkout.payment': 'చెల్లింపు విధానం',
    'checkout.upi': 'UPI చెల్లింపు',
    'checkout.upiDesc': 'UPI ద్వారా చెల్లించి స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    'checkout.cod': 'క్యాష్ ఆన్ డెలివరీ',
    'checkout.codDesc': 'డెలివరీ సమయంలో నగదు చెల్లింపు',
    'checkout.payTo': 'UPI IDకి చెల్లించండి',
    'checkout.amount': 'మొత్తం',
    'checkout.uploadHint': 'తర్వాత చెల్లింపు స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి.',
    'checkout.uploadRequired': 'దయచేసి UPI చెల్లింపు స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి.',
    'checkout.uploadBtn': 'చెల్లింపు స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    'checkout.uploadSub': 'JPG, PNG అనుమతిస్తాం',
    'checkout.agentTitle': 'నిర్ధారణ కోసం మా ఏజెంట్ కాల్ చేస్తారు',
    'checkout.agentDesc': 'ఆర్డర్ తర్వాత మా టీమ్ {phone}కి కాల్ చేస్తారు. ఫోన్ అందుబాటులో ఉంచండి.',
    'checkout.geoUnsupported': 'మీ బ్రౌజర్‌లో జియోలొకేషన్ సపోర్ట్ లేదు.',
    'checkout.geoError': 'లొకేషన్ లభించలేదు. దయచేసి అనుమతి ఇవ్వండి.',
    'checkout.summary': 'ఆర్డర్ సంగ్రహం',
    'checkout.subtotal': 'సబ్‌టోటల్',
    'checkout.shipping': 'షిప్పింగ్',
    'checkout.shippingDiscuss': 'చర్చించి నిర్ణయిస్తాం',
    'checkout.shippingFree': 'ఉచితం',
    'checkout.total': 'మొత్తం',
    'checkout.placeCod': 'COD ఆర్డర్ చేయండి',
    'checkout.confirmUpi': 'WhatsAppలో UPI ఆర్డర్ నిర్ధారించండి',
    'checkout.placing': 'ఆర్డర్ చేయబడుతోంది…',
    'checkout.backToCart': '← కార్ట్‌కు తిరిగి',
    'checkout.noteCod': 'డిస్పాచ్ ముందు నిర్ధారణ కోసం కాల్ చేస్తారు.',
    'checkout.noteUpi': 'ఆర్డర్ మరియు చెల్లింపు స్క్రీన్‌షాట్ WhatsAppలో పంపబడతాయి.',
    'checkout.loginRequiredTitle': 'సైన్ ఇన్ అవసరం',
    'checkout.loginRequiredBody': 'బుకింగ్‌కి ఫోన్ నిర్ధారణ తప్పనిసరి. దయచేసి మీ ఫోన్ నంబర్‌తో సైన్ ఇన్ చేయండి.',
    'checkout.loginCta': 'సైన్ ఇన్',
    'checkout.phoneMismatch': 'ఆర్డర్ పెట్టడానికి మీరు సైన్ ఇన్ చేసిన అదే ఫోన్ నంబర్‌ను ఉపయోగించండి.',
    'checkout.phoneLocked': 'ఫోన్ నంబర్ ధృవీకరించబడింది. మార్చడానికి సైన్ అవుట్ చేసి మళ్లీ సైన్ ఇన్ చేయండి.',
    'checkout.registeredNumber': 'మీ నమోదు చేసిన నంబర్',
    'checkout.namePlaceholder': 'ఉదా. రాహుల్ వర్మా',
    'checkout.phonePlaceholder': '9876543210',
    'checkout.emailPlaceholder': 'rahul@email.com',
    'checkout.addressPlaceholder': 'ఇల్లు నం., వీధి, ప్రాంతం',
    'checkout.cityPlaceholder': 'బెంగళూరు',
    'checkout.statePlaceholder': 'కర్ణాటక',
    'checkout.pincodePlaceholder': '560001',
    'whatsapp.newCod': '🛒 *కొత్త COD ఆర్డర్ — BR Fresh Extracts*',
    'whatsapp.newUpi': '🛒 *కొత్త UPI ఆర్డర్ — BR Fresh Extracts*',
    'whatsapp.orderId': '*ఆర్డర్ ID:* {id}',
    'whatsapp.name': '*పేరు:* {name}',
    'whatsapp.phone': '*ఫోన్:* {phone}',
    'whatsapp.email': '*ఈమెయిల్:* {email}',
    'whatsapp.addressTitle': '*డెలివరీ చిరునామా:*',
    'whatsapp.location': '📍 లొకేషన్: {link}',
    'whatsapp.detailsTitle': '*ఆర్డర్ వివరాలు:*',
    'whatsapp.subtotal': '*సబ్‌టోటల్:* ₹{amount}',
    'whatsapp.shipping': '*షిప్పింగ్:* {amount}',
    'whatsapp.shippingDiscuss': '📦 షిప్పింగ్ ఛార్జీలు డిస్పాచ్ ముందు తెలియజేస్తాం.',
    'whatsapp.total': '*మొత్తం:* ₹{amount}',
    'whatsapp.codNote': '🚚 *చెల్లింపు: COD* — కస్టమర్‌కు కాల్ చేసి నిర్ధారించండి.',
    'whatsapp.upiNote': '💳 *చెల్లింపు: UPI* — స్క్రీన్‌షాట్ చూసి నిర్ధారించండి.',
    'login.customerTab': 'కస్టమర్ OTP',
    'login.adminTab': 'అడ్మిన్ లాగిన్',
    'login.adminTitle': 'అడ్మిన్ సైన్ ఇన్',
    'login.adminSub': 'అడ్మిన్ డ్యాష్‌బోర్డ్ యాక్సెస్ చేయండి',
    'login.fullName': 'పూర్తి పేరు',
    'login.phone': 'ఫోన్ నంబర్',
    'login.phonePlaceholder': '10 అంకెల ఫోన్ నంబర్',
    'login.emailOptional': 'ఈమెయిల్ (ఐచ్ఛికం)',
    'login.adminEmail': 'అడ్మిన్ ఈమెయిల్',
    'login.adminPassword': 'అడ్మిన్ పాస్‌వర్డ్',
    'login.namePlaceholder': 'ఉదా. రాహుల్ వర్మా',
    'login.emailPlaceholder': 'you@example.com',
    'login.otpPlaceholder': '123456',
    'login.adminEmailPlaceholder': 'admin@example.com',
    'login.passwordPlaceholder': '••••••••',
    'login.sendOtp': 'OTP పంపండి',
    'login.verifyOtp': 'OTP నిర్ధారించండి',
    'login.otpLabel': 'OTP కోడ్',
    'login.resendOtp': 'OTP మళ్లీ పంపండి',
    'login.changePhone': '← నంబర్ మార్చండి',
    'login.otpSentTo': 'OTP పంపబడింది',
    'login.otpHint': 'మీ ఫోన్‌కు పంపిన 6-అంకెల కోడ్ నమోదు చేయండి',
    'login.firebaseMissing': 'Firebase keys జోడించి మళ్లీ ప్రయత్నించండి.',
    'login.adminSignIn': 'అడ్మిన్‌గా సైన్ ఇన్',
    'login.noAccount': 'ఖాతా లేదా? ',
    'login.haveAccount': 'ఇప్పటికే ఖాతా ఉందా? ',
    'login.signUpLink': 'సైన్ అప్',
    'login.signInLink': 'సైన్ ఇన్',
  }
};

const languageLabels = { en: 'EN', hi: 'हिंदी', te: 'తెలుగు' };

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('so_lang') || 'en'; } catch { return 'en'; }
  });
  const [autoMap, setAutoMap] = useState({});
  const pending = useRef(new Set());

  const setLanguage = (next) => {
    setLang(next);
    try { localStorage.setItem('so_lang', next); } catch { /* ignore */ }
  };

  useEffect(() => {
    if (lang === 'en') {
      setAutoMap({});
      return;
    }
    try {
      const stored = localStorage.getItem(`so_translate_${lang}`);
      setAutoMap(stored ? JSON.parse(stored) : {});
    } catch {
      setAutoMap({});
    }
  }, [lang]);

  const interpolate = (template, vars = {}) =>
    template.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? '');

  const translateRemote = async (text, target) => {
    try {
      const res = await fetch(`${API_URL}translate/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, target, source: 'en' }),
      });
      if (!res.ok) return null;
      const data = await res.json();
      return data.translatedText || null;
    } catch {
      return null;
    }
  };

  const cacheTranslation = (text, translated) => {
    setAutoMap(prev => {
      const next = { ...prev, [text]: translated };
      try { localStorage.setItem(`so_translate_${lang}`, JSON.stringify(next)); } catch { /* ignore */ }
      return next;
    });
  };

  const tr = useMemo(() => (text) => {
    if (!text) return '';
    if (lang === 'en') return text;
    if (autoMap[text]) return autoMap[text];
    if (pending.current.has(text)) return text;
    pending.current.add(text);
    translateRemote(text, lang).then((translated) => {
      if (translated) cacheTranslation(text, translated);
      pending.current.delete(text);
    });
    return text;
  }, [lang, autoMap]);

  const translateAsync = async (text) => {
    if (!text) return '';
    if (lang === 'en') return text;
    if (autoMap[text]) return autoMap[text];
    const translated = await translateRemote(text, lang);
    if (translated) cacheTranslation(text, translated);
    return translated || text;
  };

  const t = useMemo(() => (key, vars = {}) => {
    const base = translations.en[key] || key;
    if (lang === 'en') return interpolate(base, vars);
    const manual = translations[lang]?.[key];
    if (manual) return interpolate(manual, vars);
    return interpolate(tr(base), vars);
  }, [lang, tr]);

  const value = useMemo(() => ({ lang, setLang: setLanguage, t, tr, translateAsync, languages: languageLabels }), [lang, t, tr, translateAsync]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
